apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "{{ .Release.Name }}"
  labels:
    {{- include "go-sample-site.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "go-sample-site.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "go-sample-site.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}        
      {{- end }}
      serviceAccountName: {{ .Values.github.knownHost | default "" | quote }}
      containers:
        - name: go-sample-site
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
